/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ccmdb.auth;

import java.awt.Color;

/**
 *
 * @author ALCra
 */
class LoginUI extends javax.swing.JFrame {
    LoginInterface loginListener;

    /**
     * Creates new form LoginUI
     */
    LoginUI(LoginHandler handler) {
        loginListener = (LoginInterface) handler;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        LoginTitleText = new javax.swing.JLabel();
        LoginPerformAuthButton = new javax.swing.JButton();
        LoginExitButton = new javax.swing.JButton();
        LoginUsernameInputField = new javax.swing.JTextField();
        LoginPasswordInputField = new javax.swing.JPasswordField();
        LoginErrorMessageText = new javax.swing.JLabel();
        LoginPasswordText = new javax.swing.JLabel();
        LoginUsernameText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setMaximumSize(new java.awt.Dimension(322, 212));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        LoginTitleText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LoginTitleText.setText("Please Login");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        getContentPane().add(LoginTitleText, gridBagConstraints);

        LoginPerformAuthButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LoginPerformAuthButton.setText("Login");
        LoginPerformAuthButton.setToolTipText("");
        LoginPerformAuthButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginPerformAuthButtonMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        getContentPane().add(LoginPerformAuthButton, gridBagConstraints);

        LoginExitButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LoginExitButton.setText("Exit");
        LoginExitButton.setToolTipText("");
        LoginExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginExitButtonMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        getContentPane().add(LoginExitButton, gridBagConstraints);

        LoginUsernameInputField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(LoginUsernameInputField, gridBagConstraints);

        LoginPasswordInputField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(LoginPasswordInputField, gridBagConstraints);

        LoginErrorMessageText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LoginErrorMessageText.setForeground(new java.awt.Color(240, 240, 240));
        LoginErrorMessageText.setText("Incorrect username or password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 4, 0);
        getContentPane().add(LoginErrorMessageText, gridBagConstraints);

        LoginPasswordText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LoginPasswordText.setText("Password :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        getContentPane().add(LoginPasswordText, gridBagConstraints);

        LoginUsernameText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LoginUsernameText.setText("Username :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        getContentPane().add(LoginUsernameText, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginPerformAuthButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginPerformAuthButtonMouseClicked
        // TODO add your handling code here:
        if(!loginListener.verifyLoginCredentials(LoginUsernameInputField.getText(), LoginPasswordInputField.getPassword())){
            LoginErrorMessageText.setForeground(Color.red);
        }  
    }//GEN-LAST:event_LoginPerformAuthButtonMouseClicked

    private void LoginExitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginExitButtonMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_LoginExitButtonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LoginErrorMessageText;
    private javax.swing.JButton LoginExitButton;
    private javax.swing.JPasswordField LoginPasswordInputField;
    private javax.swing.JLabel LoginPasswordText;
    private javax.swing.JButton LoginPerformAuthButton;
    private javax.swing.JLabel LoginTitleText;
    private javax.swing.JTextField LoginUsernameInputField;
    private javax.swing.JLabel LoginUsernameText;
    // End of variables declaration//GEN-END:variables
}
